apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentrix-lab
  namespace: default
  labels:
    app: zentrix
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zentrix
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zentrix
    spec:
      containers:
        - name: lab-container
          image: crpi-nfo20s3jyve6dt2s.cn-beijing.personal.cr.aliyuncs.com/zentrix-repo/devops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/logs
              name: access-logs
      imagePullSecrets:
        - name: aliyun-registry-secret
      volumes:
        - name: access-logs
          hostPath:
            path: /data/zentrix/logs
            type: DirectoryOrCreate
