apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zentrix-main-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/forwarded-for-header: CF-Connecting-IP
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: zentrix-service
                port:
                  number: 80
            path: /
            pathType: Prefix
