apiVersion: v1
kind: Service
metadata:
  name: zentrix-service
  namespace: default
  labels:
    app: zentrix
spec:
  ports:
    - nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: zentrix
  type: NodePort
