<template>
  <main class="notes-page">
    <section class="notes-hero">
      <div><p class="notes-eyebrow">个人灵感档案</p><h1>灵感收集</h1><p>按月留下那些不必立刻完成、但值得被保存和回看的念头。</p></div>
      <div class="notes-summary"><div><strong>{{ notes.length }}</strong><span>总计</span></div><div><strong>{{ ideaCount }}</strong><span>个想法</span></div><div><strong>{{ vibeCount }}</strong><span>个 Vibe Coding</span></div><div><strong>{{ memoCount }}</strong><span>个备忘</span></div><div><strong>{{ dreamCount }}</strong><span>个梦</span></div></div>
      <div class="notes-actions"><button class="notes-button notes-button--quiet" type="button" @click="exportNotes">导出 JSON</button><button class="notes-button" type="button" @click="startNew">记录灵感</button></div>
    </section>
    <section class="notes-toolbar" aria-label="备忘筛选">
      <label>月份<input v-model="monthKey" type="month" @change="loadNotes" /></label><label class="notes-search">搜索<input v-model.trim="searchQuery" type="search" placeholder="搜索标题、详情或标签" /></label>
      <div class="notes-filters" role="group" aria-label="分类筛选"><button v-for="item in filters" :key="item.value" type="button" :class="{ active: filter === item.value }" @click="filter = item.value">{{ item.label }}</button></div>
      <div class="notes-view-switch" role="group" aria-label="查看方式"><button type="button" :class="{ active: viewMode === 'list' }" @click="viewMode = 'list'">列表</button><button type="button" :class="{ active: viewMode === 'calendar' }" @click="viewMode = 'calendar'">时间轴</button><button type="button" :class="{ active: viewMode === 'activity' }" @click="openActivity">记录节奏</button></div><button class="notes-ai" type="button" :disabled="analyzing" @click="analyzeMonth">{{ analyzing ? '分析中…' : 'AI 分析本月' }}</button>
    </section>
    <div v-if="availableTags.length" class="notes-tag-filter" aria-label="标签筛选"><span>标签</span><button type="button" :class="{ active: !activeTag }" @click="activeTag = ''">全部</button><button v-for="tag in availableTags" :key="tag" type="button" :class="{ active: activeTag === tag }" @click="activeTag = activeTag === tag ? '' : tag"># {{ tag }}</button></div>
    <section v-if="report" class="notes-report" aria-live="polite"><div><p class="notes-eyebrow">AI 视角</p><h2>{{ monthLabel }} 的主题梳理</h2></div><button type="button" class="notes-close" aria-label="关闭 AI 分析" @click="report = ''">关闭</button><MarkdownContent :content="report" /></section>
    <section v-if="loading" class="notes-empty">正在读取你的灵感档案…</section>
    <section v-else-if="viewMode === 'activity'" class="notes-activity" aria-labelledby="notes-activity-title"><div class="notes-activity__heading"><div><p class="notes-eyebrow">记录节奏</p><h2 id="notes-activity-title">{{ activityMonthLabel }} 每日记录</h2></div><div class="notes-activity__month"><button type="button" aria-label="上一个月" @click="shiftActivityMonth(-1)">←</button><input v-model="activityMonthKey" type="month" aria-label="记录节奏月份" @change="loadActivityNotes" /><button type="button" aria-label="下一个月" @click="shiftActivityMonth(1)">→</button></div></div><p class="notes-activity__summary">{{ activeDays }} 天有记录 · 共 {{ activityNotes.length }} 条</p><div class="notes-activity__chart" role="img" :aria-label="`${activityMonthLabel}每日记录柱状图，共 ${activityNotes.length} 条，${activeDays} 天有记录`"><div v-for="day in dailyCounts" :key="day.day" class="notes-activity__column" :title="`${day.label}：${day.count} 条`" :style="{ '--bar-height': `${day.height}%` }"><span v-if="day.count" class="notes-activity__count">{{ day.count }}</span><i></i><small v-if="day.showLabel">{{ day.day }}</small></div></div></section>
    <section v-else-if="viewMode === 'calendar'" class="notes-timeline" aria-label="时间轴视图"><button v-for="note in timelineNotes" :key="note.id" type="button" :class="['notes-timeline__row', noteStatusClass(note)]" @click="openDetail(note)"><time>{{ formatShortDate(note.updatedAt) }}</time><span :class="['note-category', note.category]">{{ categoryLabel(note.category) }}</span><span class="notes-timeline__main"><b>{{ note.title }}</b><small v-if="note.content">{{ timelinePreview(note.content) }}</small><em v-if="note.tags?.length">{{ note.tags.slice(0, 2).map((tag) => `#${tag}`).join(' ') }}</em></span><span v-if="note.status === 'done'" class="notes-calendar__check" aria-label="已完成">✓</span></button><p v-if="!timelineNotes.length">当前筛选没有记录。</p></section>
    <section v-else-if="filteredNotes.length" class="notes-list" aria-label="备忘列表"><article v-for="note in filteredNotes" :key="note.id" :class="['note-card', noteStatusClass(note)]" tabindex="0" role="button" :aria-label="`查看备忘：${note.title}`" @click="openDetail(note)" @keydown.enter="openDetail(note)" @keydown.space.prevent="openDetail(note)"><span v-if="note.status === 'done'" class="note-done" aria-label="已完成">✓</span><div class="note-card__meta"><span :class="['note-category', note.category]">{{ categoryLabel(note.category) }}</span><span v-if="note.status && note.status !== 'done'" :class="['note-status', note.status]">{{ statusLabel(note.status) }}</span></div><h2>{{ note.title }}</h2><p v-if="note.content">{{ note.content }}</p><div v-if="note.tags?.length" class="note-tags"><span v-for="tag in note.tags" :key="tag"># {{ tag }}</span></div><footer><time :datetime="note.updatedAt">更新于 {{ formatShortDate(note.updatedAt) }}</time><span><button type="button" @click.stop="editNote(note)">编辑</button><button class="danger" type="button" @click.stop="removeNote(note)">删除</button></span></footer></article></section>
    <section v-else class="notes-empty"><h2>这个月份还是空白</h2><p>先记一条不需要立即行动的想法。它会在合适的时候重新出现。</p><div><button class="notes-button" type="button" @click="startNew">记录第一条</button><button v-if="canImportSamples && !notes.length" class="notes-button notes-button--quiet" type="button" @click="seedAugust">导入 2026 年 8 月示例</button></div></section>
    <Teleport to="body"><div v-if="detail || editing || creating" class="note-modal-backdrop" role="presentation" @click.self="closeModal"><section class="note-detail" :class="{ 'note-detail--editing': editing || creating, 'note-detail--view': detail }" role="dialog" aria-modal="true" :aria-label="detail ? `查看备忘：${detail.title}` : '编辑记录'"><button class="note-detail__close" type="button" aria-label="关闭" @click="closeModal">×</button><NoteEditor v-if="editing" v-model:note="editing" :saving="saving" :error="formError" @save="saveNote" @cancel="closeModal" /><NoteEditor v-else-if="creating" v-model:note="creating" :saving="saving" :error="formError" :draft-key="draftStorageKey(creating)" @save="saveNote" @cancel="closeModal" /><template v-else-if="detail"><div class="note-detail__hero"><div class="note-card__meta"><span :class="['note-category', detail.category]">{{ categoryLabel(detail.category) }}</span></div><h2>{{ detail.title }}</h2></div><div class="note-detail__body"><section class="note-detail__section"><h3 class="note-detail__label">详情</h3><p class="note-detail__content">{{ detail.content || '这条记录暂时没有补充内容。' }}</p></section><section v-if="detail.tags?.length" class="note-detail__section"><h3 class="note-detail__label">标签</h3><div class="note-tags"><span v-for="tag in detail.tags" :key="tag"># {{ tag }}</span></div></section><section v-if="detail.images?.length" class="note-detail__section"><h3 class="note-detail__label">图片</h3><div class="note-detail__images"><figure v-for="image in detail.images" :key="image.id"><a :href="image.url" target="_blank" rel="noopener" :aria-label="`查看图片：${image.fileName}`"><img :src="image.url" :alt="image.fileName" loading="lazy" /></a><figcaption><span>{{ image.fileName }}</span><button type="button" :disabled="saving" :aria-label="`从记录移除图片：${image.fileName}`" @click="hideDetailImage(image)">移除</button></figcaption></figure></div></section><p class="note-detail__updated">最后编辑 <time :datetime="detail.updatedAt">{{ formatDateTime(detail.updatedAt) }}</time></p><nav class="note-detail__pager" aria-label="浏览记录"><button type="button" :disabled="!hasPreviousDetail" @click="openAdjacentDetail(-1)">← 上一条</button><span>{{ detailPosition }}</span><button type="button" :disabled="!hasNextDetail" @click="openAdjacentDetail(1)">下一条 →</button></nav><footer><button class="notes-button notes-button--quiet" type="button" @click="shareDetail">导出图片</button><button class="notes-button" type="button" @click="editFromDetail">编辑</button></footer></div></template></section></div></Teleport>
    <SharePreviewModal :preview="sharePreview" @close="sharePreview = null" @download="downloadSharePreview" />
  </main>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import MarkdownContent from '../../../components/MarkdownContent.vue'
import { useToast } from '../../../composables/useToast.js'
import { notesApi } from '../api/notes.js'
import NoteEditor from '../components/NoteEditor.vue'
import SharePreviewModal from '../components/SharePreviewModal.vue'
import { createNoteImage, downloadNoteImage } from '../utils/shareNoteImage.js'

const toast = useToast(); const canImportSamples = import.meta.env.DEV
const monthKey = ref(new Date().toISOString().slice(0, 7)); const activityMonthKey = ref(monthKey.value); const notes = ref([]); const activityNotes = ref([]); const filter = ref('all'); const activeTag = ref(''); const searchQuery = ref(''); const viewMode = ref('list'); const loading = ref(true); const saving = ref(false); const analyzing = ref(false); const report = ref(''); const formError = ref(''); const creating = ref(null); const editing = ref(null); const detail = ref(null); const sharePreview = ref(null)
const filters = [{ value: 'all', label: '全部' }, { value: 'idea', label: '想法' }, { value: 'vibe_coding', label: 'Vibe Coding' }, { value: 'memo', label: '备忘' }, { value: 'dream', label: '梦' }]
const normalizedSearch = computed(() => searchQuery.value.trim().toLocaleLowerCase())
const availableTags = computed(() => [...new Set(notes.value.flatMap((note) => note.tags || []))].sort((a, b) => a.localeCompare(b, 'zh-CN')))
const filteredNotes = computed(() => notes.value.filter((note) => { if (filter.value !== 'all' && note.category !== filter.value) return false; if (activeTag.value && !(note.tags || []).includes(activeTag.value)) return false; return !normalizedSearch.value || [note.title, note.content, ...(note.tags || [])].join(' ').toLocaleLowerCase().includes(normalizedSearch.value) }))
const timelineNotes = computed(() => [...filteredNotes.value].sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt))))
const detailIndex = computed(() => timelineNotes.value.findIndex((note) => note.id === detail.value?.id)); const detailPosition = computed(() => detailIndex.value < 0 ? '' : `${detailIndex.value + 1} / ${timelineNotes.value.length}`); const hasPreviousDetail = computed(() => detailIndex.value > 0); const hasNextDetail = computed(() => detailIndex.value >= 0 && detailIndex.value < timelineNotes.value.length - 1)
const ideaCount = computed(() => notes.value.filter((note) => note.category === 'idea').length); const vibeCount = computed(() => notes.value.filter((note) => note.category === 'vibe_coding').length); const memoCount = computed(() => notes.value.filter((note) => note.category === 'memo').length); const dreamCount = computed(() => notes.value.filter((note) => note.category === 'dream').length); const monthLabel = computed(() => monthKey.value.replace('-', ' 年 ') + ' 月'); const activityMonthLabel = computed(() => activityMonthKey.value.replace('-', ' 年 ') + ' 月')
const dailyCounts = computed(() => { const [year, month] = activityMonthKey.value.split('-').map(Number); const days = new Date(year, month, 0).getDate(); const counts = Array.from({ length: days }, (_, index) => ({ day: index + 1, count: 0 })); activityNotes.value.forEach((note) => { const date = new Date(note.createdAt); if (date.getFullYear() === year && date.getMonth() + 1 === month) counts[date.getDate() - 1].count += 1 }); const max = Math.max(...counts.map((item) => item.count), 1); return counts.map((item) => ({ ...item, label: `${month} 月 ${item.day} 日`, height: item.count ? Math.max(12, Math.round((item.count / max) * 100)) : 0, showLabel: item.day === 1 || item.day === days || item.day % 5 === 0 })) })
const activeDays = computed(() => dailyCounts.value.filter((item) => item.count > 0).length)
const blank = () => ({ monthKey: monthKey.value, category: 'idea', status: '', tags: [], title: '', content: '', images: [], pendingImages: [], removedImageIds: [] }); const categoryLabel = (category) => ({ idea: '想法', vibe_coding: 'Vibe Coding', memo: '备忘', dream: '梦' })[category] || '想法'; const statusLabel = (status) => ({ done: '已完成', impossible: '不可能', uncertain: '不确定' })[status] || '未定'; const noteStatusClass = (note) => note.category === 'vibe_coding' && note.status ? `note-status--${note.status}` : ''; const formatShortDate = (value) => new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).format(new Date(value)).replaceAll(',', ''); const formatDateTime = (value) => new Intl.DateTimeFormat('zh-CN', { dateStyle: 'long', timeStyle: 'short' }).format(new Date(value)); const timelinePreview = (content) => content.length > 62 ? `${content.slice(0, 62)}…` : content; const draftStorageKey = (note) => `zentrix-notes:draft:${note.monthKey}`
async function loadNotes() { loading.value = true; activeTag.value = ''; try { notes.value = (await notesApi.list(monthKey.value)).notes || [] } catch (error) { toast.error(error.message) } finally { loading.value = false } }
async function loadActivityNotes() { try { activityNotes.value = activityMonthKey.value === monthKey.value ? notes.value : ((await notesApi.list(activityMonthKey.value)).notes || []) } catch (error) { toast.error(error.message) } }
async function openActivity() { activityMonthKey.value = monthKey.value; viewMode.value = 'activity'; await loadActivityNotes() }
function shiftActivityMonth(offset) { const [year, month] = activityMonthKey.value.split('-').map(Number); const next = new Date(year, month - 1 + offset, 1); activityMonthKey.value = `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}`; loadActivityNotes() }
function startNew() { formError.value = ''; detail.value = null; editing.value = null; creating.value = blank() }; function openDetail(note) { detail.value = { ...note, tags: [...(note.tags || [])], images: [...(note.images || [])] } }; function openAdjacentDetail(offset) { const next = timelineNotes.value[detailIndex.value + offset]; if (next) openDetail(next) }; function editNote(note) { formError.value = ''; creating.value = null; editing.value = { ...note, tags: [...(note.tags || [])], images: [...(note.images || [])], pendingImages: [], removedImageIds: [], status: note.status || '' } }; function editFromDetail() { const note = detail.value; detail.value = null; editNote(note) }; function closeModal() { sharePreview.value = null; detail.value = null; editing.value = null; creating.value = null; formError.value = '' }
async function saveNote() { const target = editing.value || creating.value; if (!target?.title.trim()) { formError.value = '请先写下这条记录的标题。'; return }; saving.value = true; try { const wasNew = !target.id; const { images = [], pendingImages = [], removedImageIds = [], ...payload } = target; payload.status = payload.category === 'vibe_coding' ? payload.status : null; const result = target.id ? await notesApi.update(target.id, payload) : await notesApi.create(payload); const currentImages = [...images]; Object.assign(target, result.note, { images: currentImages, pendingImages: [...pendingImages], removedImageIds: [...removedImageIds] }); for (const imageId of removedImageIds) await notesApi.removeImage(result.note.id, imageId); target.removedImageIds = []; for (let index = 0; index < pendingImages.length; index += 1) { const { image } = await notesApi.uploadImage(result.note.id, pendingImages[index]); currentImages.push(image); target.images = [...currentImages]; target.pendingImages = pendingImages.slice(index + 1) } result.note.images = currentImages; const noteIndex = notes.value.findIndex((item) => item.id === result.note.id); if (noteIndex >= 0) notes.value.splice(noteIndex, 1, result.note); else notes.value.unshift(result.note); if (wasNew) localStorage.removeItem(draftStorageKey(target)); editing.value = null; creating.value = null; toast.success(`已保存于 ${formatShortDate(result.note.updatedAt)}`) } catch (error) { formError.value = error.message } finally { saving.value = false } }
async function removeNote(note) { if (!window.confirm(`确定删除「${note.title}」吗？`)) return; try { await notesApi.remove(note.id); notes.value = notes.value.filter((item) => item.id !== note.id); toast.success('已删除') } catch (error) { toast.error(error.message) } }; async function hideDetailImage(image) { if (!window.confirm(`确定移除「${image.fileName}」？`)) return; saving.value = true; try { const result = await notesApi.removeImage(detail.value.id, image.id); detail.value.images = detail.value.images.filter((item) => item.id !== image.id); if (result.note) { detail.value.updatedAt = result.note.updatedAt; const index = notes.value.findIndex((item) => item.id === detail.value.id); if (index >= 0) notes.value.splice(index, 1, { ...notes.value[index], images: [...detail.value.images], updatedAt: result.note.updatedAt }) } toast.success('图片已移除') } catch (error) { toast.error(error.message) } finally { saving.value = false } }; async function analyzeMonth() { analyzing.value = true; try { report.value = (await notesApi.analyze(monthKey.value)).report } catch (error) { toast.error(error.message) } finally { analyzing.value = false } }; async function seedAugust() { try { notes.value = (await notesApi.seedAugust()).notes || []; monthKey.value = '2026-08'; toast.success('已导入 84 条 8 月示例') } catch (error) { toast.error(error.message) } }; function exportNotes() { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), notes: notes.value }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `灵感收集-${monthKey.value}.json`; link.click(); URL.revokeObjectURL(url) }; async function shareDetail() { try { sharePreview.value = await createNoteImage(detail.value, { categoryLabel, statusLabel }) } catch { toast.error('分享图片生成失败，请稍后重试') } }; function downloadSharePreview() { downloadNoteImage(sharePreview.value); toast.success('图片已下载到本地') }; function handleKeydown(event) { if (!detail.value || editing.value || creating.value) return; if (event.key === 'Escape') closeModal(); if (event.key === 'ArrowLeft') openAdjacentDetail(-1); if (event.key === 'ArrowRight') openAdjacentDetail(1) }
onMounted(() => { loadNotes(); window.addEventListener('keydown', handleKeydown) }); onBeforeUnmount(() => window.removeEventListener('keydown', handleKeydown))
</script>
